// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTeZYGjeLqSzAAU39qiNShnxoYYv-G624',
    appId: '1:184167105170:web:b37818f56f50ca7c95dc4b',
    messagingSenderId: '184167105170',
    projectId: 'time-mind',
    authDomain: 'time-mind.firebaseapp.com',
    storageBucket: 'time-mind.firebasestorage.app',
    measurementId: 'G-S6H9N0G3DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrtel1jOUUHugYqUoegfoOsvJJ7CdbP5I',
    appId: '1:184167105170:android:6151d7601f9ce0d695dc4b',
    messagingSenderId: '184167105170',
    projectId: 'time-mind',
    storageBucket: 'time-mind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaqCOHCbiujl9k8e4pcqpQsAqmSPZ4nZ4',
    appId: '1:184167105170:ios:0eca7c2ae66005a895dc4b',
    messagingSenderId: '184167105170',
    projectId: 'time-mind',
    storageBucket: 'time-mind.firebasestorage.app',
    iosBundleId: 'com.example.timeMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaqCOHCbiujl9k8e4pcqpQsAqmSPZ4nZ4',
    appId: '1:184167105170:ios:0eca7c2ae66005a895dc4b',
    messagingSenderId: '184167105170',
    projectId: 'time-mind',
    storageBucket: 'time-mind.firebasestorage.app',
    iosBundleId: 'com.example.timeMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTeZYGjeLqSzAAU39qiNShnxoYYv-G624',
    appId: '1:184167105170:web:6fe0e1defcecb39595dc4b',
    messagingSenderId: '184167105170',
    projectId: 'time-mind',
    authDomain: 'time-mind.firebaseapp.com',
    storageBucket: 'time-mind.firebasestorage.app',
    measurementId: 'G-PQEQ3Q55PS',
  );
}
