CREATE TABLE "user" (
  "id" integer PRIMARY KEY,
  "username" varchar,
  "email" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "devices" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "platform_type_id" integer,
  "browser_type_id" integer,
  "browser_version" varchar(20),
  "os_version" varchar(20),
  "device_model" varchar(50),
  "push_service" varchar(20),
  "push_capabilities" json,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "user_devices" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "device_id" integer,
  "first_used_at" timestamp DEFAULT (now()),
  "last_used_at" timestamp,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "user_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "user_device_id" integer,
  "session_token" varchar(512) UNIQUE,
  "ip_address" varchar(45),
  "location" varchar(100),
  "is_active" boolean DEFAULT true,
  "login_at" timestamp DEFAULT (now()),
  "logout_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "push_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_device_id" integer,
  "token" varchar(512) UNIQUE,
  "token_type" varchar(20),
  "is_active" boolean DEFAULT true,
  "last_used_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "notification_settings" (
  "user_id" integer,
  "device_id" integer,
  "enable_push" boolean DEFAULT true,
  "enable_email" boolean DEFAULT false,
  "notification_categories_id" integer,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "platform_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50)
);

CREATE TABLE "browser_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code_name" varchar(20) UNIQUE,
  "name" varchar(50)
);

CREATE TABLE "notification_categories" (
  "id" integer PRIMARY KEY,
  "code_name" varchar(30) UNIQUE,
  "name" varchar(100)
);

CREATE TABLE "state" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "heart_rate" integer,
  "mood" integer,
  "app_usage" interval,
  "mindfulness_score" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "sleep_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "sleep_start" timestamp,
  "sleep_end" timestamp,
  "duration" interval,
  "deep_sleep_duration" interval,
  "light_sleep_duration" interval,
  "rem_sleep_duration" interval,
  "awake_duration" interval,
  "source" varchar(50),
  "quality_score" integer,
  "noise_level" integer,
  "wake_up_count" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "steps_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "steps_count" integer,
  "distance_meters" integer,
  "calories_burned" integer,
  "data_source" varchar(50),
  "recorded_at" date,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "apps_usage" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "device_id" integer,
  "platform" varchar(20),
  "app_id" varchar(255),
  "app_name" varchar(255),
  "app_category" varchar(100),
  "date" date,
  "usage_time" bigint,
  "session_count" integer,
  "avg_session_length" bigint,
  "foreground_time" bigint,
  "background_time" bigint,
  "percent_of_total" float,
  "notifications_count" integer,
  "domain" varchar(255),
  "visits_count" integer,
  "active_time_on_site" bigint,
  "total_time_on_site" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX ON "user_devices" ("user_id", "device_id");

CREATE INDEX ON "user_sessions" ("user_id", "is_active");

CREATE INDEX ON "user_sessions" ("session_token");

CREATE INDEX ON "push_tokens" ("user_device_id", "is_active");

CREATE INDEX ON "state" ("user_id", "created_at");

CREATE INDEX ON "sleep_log" ("user_id", "sleep_start");

CREATE INDEX ON "steps_log" ("user_id", "recorded_at");

CREATE INDEX ON "apps_usage" ("user_id", "app_id", "date");

ALTER TABLE "devices" ADD FOREIGN KEY ("platform_type_id") REFERENCES "platform_types" ("id");

ALTER TABLE "devices" ADD FOREIGN KEY ("browser_type_id") REFERENCES "browser_types" ("id");

ALTER TABLE "user_devices" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_devices" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");

ALTER TABLE "user_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_sessions" ADD FOREIGN KEY ("user_device_id") REFERENCES "user_devices" ("id");

ALTER TABLE "push_tokens" ADD FOREIGN KEY ("user_device_id") REFERENCES "user_devices" ("id");

ALTER TABLE "notification_settings" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "notification_settings" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");

ALTER TABLE "notification_settings" ADD FOREIGN KEY ("notification_categories_id") REFERENCES "notification_categories" ("id");

ALTER TABLE "state" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "sleep_log" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "steps_log" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "apps_usage" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "apps_usage" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");
